
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "packages"
    label: "Packages"
    folder: "packages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image URL", name: "image", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
